MAP_WIDTH = 40
MAP_HEIGHT = 20
MAP_BLOCK_X = 4
MAP_BLOCK_Y = 1
SCREEN_BLOCK_WIDTH = MAP_WIDTH+MAP_BLOCK_X+1
SCREEN_BLOCK_HEIGHT = MAP_HEIGHT+MAP_BLOCK_Y+1
BLOCK_SIZE = int(1000/max(SCREEN_BLOCK_WIDTH, SCREEN_BLOCK_HEIGHT))
SCREEN_WIDTH = SCREEN_BLOCK_WIDTH*BLOCK_SIZE
SCREEN_HEIGHT = SCREEN_BLOCK_HEIGHT*BLOCK_SIZE

TIMER_ELAPSE = 10
VIEW_TIMER_ELAPSE = 10


